### ISSUE TITLE
Improvement: Improvements to site text

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#108]
### Issue Summary

@jhdalek55 I copied over the suggestions you had for the text improvements to create an issue. Perhaps a #hacktoberfest user will volunteer to make a PR for the changes.

### Details

# Home Page

## Under “Resilient Protection”... Add

- [ ] “…but follows a hierarchy in which different levels of access to vehicles or the automaker’s infrastructure must be gained before irreparable damage can be inflicted.

- [ ] There should be a question mark after “Why Uptane?”

## Under “Getting to Know Uptane,” 

- [ ] under the Publications header “whitepapers” is generally one-word.

## Under the “Adoptions” header, 

- [ ] add “A list of Uptane adopters”

- [ ] Capitalization of the main header categories is very inconsistent. With the exception of the proper noun Uptane, and the first word in each title, which must always  be capitalized, all words in the titles should be lower case. Hence, change “Getting to know Uptane,”  and “Join the Uptane community”

## Under “Putting Uptane to work” 

- [ ]  Three of tag lines under the categories still say “Short descriptions about” and the fourth is less than clear. Change these to:

> ### Uptane Standard
> The set of requirements necessary for the secure implementation of the framework
> 
> ### Deployment Best Practices
> Examples of best practices for setting up, operating, integrating, and adapting Uptane to work in a variety of situations.
> 
> ### PUREs
> A vehicle for proposing an addition to or modification of the Uptane Standard.
> 
> ### POUFs
> A mechanism to describe the protocols, operations, usage, and formats of an Uptane implementation.

## Under “Join the Uptane community” 

- [ ] The word “Uptane” in the sentence that follows must be capitalized

- [x] Also, why is the community call listed for Fridays at 5:30? This should be Every other Tuesday at 10:00 am eastern time

- [ ] Joint Development Foundation must be capitalized. And we should use the full title here

- [ ] Joint Development Foundation Projects, LLC, Uptane Series

## On the About Us page,

- [ ] The last sentence of the “Project Contributors” page should read “Here is an alphabetical list of the primary contributors who have asked to have their names, or the names of their organizations listed.

- [ ] Also, add Renesas Electronics to the company list 
- [ ] Add Phillip Nguyen to the people list
- [ ] Correct "Phillip Lapczynski" to "Philip Lapczynski"

## On the Getting Started page

- [ ] Under Item Number 2, Learn more in the Threat Model section. The section is not called “Uptane Threat Model.” Also, the title of the page this links to should also be called “Threat Model” and not “Why Uptane is Needed”

- [ ] Under Item Number 4, the last sentence should read “Learn more in the Uptane Deployment Best Practices document.” It’s not a section.

- [ ] Under Item Number 6, Question 1, last sentence, medical and health care equipment, smart city devices, and aviation.

## On the Threat Model page

- [ ] As noted above, change the title of the document (on the page) to Threat Model.

## On the Audio Visual Page,

- [ ] Last sentence of the first paragraph needs to be changed “These include virtual programs held in October 2022 and March 2023, an in-person program held in December 2022, and a hybrid program in June 2023.” 

- [ ] We also never added the slide presentation from the June 2023 meeting. I have these on my desktop, but I’m not sure how to add them to the new site.

- [ ] The first three bullet points need to be changed from “for the Uptane conference to be held March 31, 2023” to “the Uptane conference held March 31, 2023”

## On the Contributing Page

- [ ] Under Code Contributions - I think this has already been reported, but the link under “these development instructions,” is going to the Secure Systems Lab guidelines, when it should be going to the new README.

- [ ] Under Security Audits
Please remove my Lois' name and email as maintainer.

- [ ] Under History
2016: The conference should be referred to as “escar Europe”

- [ ] 2019: Revise the following: The Uptane project  joins the Linux Foundation's Joint Development Foundation, providing a pathway for ISO standardization of future versions of the Standard.

**Comment by jhdalek55** [comment]
OK. Thanks @hexsecs

**Comment by Mikerniker** [comment]
Hi @hexsecs and @jhdalek55 

Hello, I'd like to try this if possible. Also, can I clarify the following:

1. Please verify if the files at these locations are what need changes: 
  - Home Page: -- I can't seem to find where this is located.
  - About Us:   docs/learn-more/about.md
  - Getting Started Page: docs/learn-more/getting-started.md
  - Threat Model Page: docs/learn-more/threat.md
  - Audio Visual Page:  docs/learn-more/audio.md
  - Contributing Page:  docs/learn-more/participate.md
  - History Page:  docs/learn-more/history.md

2. Do you prefer one PR per page or one PR for all the pages?

3. For more clarification for the instructions on the [Threat Model page](https://uptane.github.io/docs/learn-more/threat): "As noted above, change the title of the document (on the page) to Threat Model." The "title" here refers to: "Why Uptane is needed" -> which will be changed to "Threat Model"
4. For the second instruction for the [Audio Visual Page](https://uptane.github.io/docs/learn-more/audio),  since the slide presentations from the June 2023 meeting are not yet available, can I just skip for now or maybe this can be a separate issue for when the files are available?
5. For the [Contributing page](https://uptane.github.io/docs/learn-more/participate), in the instructions for Code Contributions, the "new README" refers to this README: https://github.com/uptane/uptane.github.io ?
- The instructions for "Under Security Audits" will change from "Please contact lab director Justin Cappos or maintainer Lois Anne DeLong." to "Please contact lab director Justin Cappos."  

6. The instructions for "Under History" refers to the [History Page](https://uptane.github.io/docs/learn-more/history) not the Contributing Page.
and to change "2016: Uptane: Securing Software Updates for Automobiles is presented at escar 16" (in the History Page) to "2016: Uptane: Securing Software Updates for Automobiles is presented at escar Europe"

Thank you

**Comment by Mikerniker** [comment]
Hi @hexsecs and @jhdalek55

I'd like to try this if possible. Also, can I clarify the following:

1. Please help verify if the files at these locations are what need changes:
  - Home Page: -- I can't seem to find where this is located.
  - About Us: docs/learn-more/about.md
  - Getting Started Page: docs/learn-more/getting-started.md
  - Threat Model Page: docs/learn-more/threat.md
  - Audio Visual Page: docs/learn-more/audio.md
  - Contributing Page: docs/learn-more/participate.md
  - History Page: docs/learn-more/history.md

2. Do you prefer one PR per page or one PR for all the pages?

3. For more clarification for the instructions on the [Threat Model page](https://uptane.github.io/docs/learn-more/threat): "As noted above, change the title of the document (on the page) to Threat Model." The "title" here refers to: "Why Uptane is needed" -> which will be changed to "Threat Model"

4. For the second instruction for the [Audio Visual Page](https://uptane.github.io/docs/learn-more/audio), since the slide presentations from the June 2023 meeting are not yet available, should I just skip for now or maybe this can be a separate issue for when the files are available?

5. For the [Contributing page](https://uptane.github.io/docs/learn-more/participate), in the instructions for Code Contributions, the "new README" refers to this README: https://github.com/uptane/uptane.github.io ?

6. To further clarify the instructions for "Under Security Audits" -  the text "Please contact lab director Justin Cappos or maintainer Lois Anne DeLong." should be changed to "Please contact lab director Justin Cappos."

7. Also, the instructions for "Under History" refers to the [History Page](https://uptane.github.io/docs/learn-more/history) not the Contributing Page.
 -->
and to change "2016: Uptane: Securing Software Updates for Automobiles is presented at escar 16" (in the History Page) to "2016: Uptane: Securing Software Updates for Automobiles is presented at escar Europe"

Thank you

**Comment by jhdalek55** [comment]
Hi @Mikerniker 
I can clarify a few of these things since I'm the one who wrote them.

The Home page refers to https://uptane.github.io/. I'm not sure what files these are under.
The other files are correct.

I think these can all be done in one PR. It's a relatively small list.

Number 3 is correct. Yes. Just change "What Uptane is Needed" to "Threat Model"

We can wait to add the new slides to the audio visual  site. I do have them as PDF files and can forward them. I just don't know the process for doing this myself.

In Number 5 , the new README refers to https://github.com/uptane/uptane.github.io/blob/uptane_docusaurus/README.md

In Number 6, yes, just drop out my name and email and end the sentence with Justin's email.

And, Number 7, yes, correct.

Thanks.

Lois

**Comment by Mikerniker** [comment]
Ok, thanks for the clarifications @jhdalek55 ! 

I **think** I may have found the location for the Home Page, and this seems to be composed of several .jsx files:

- Resilient Protection: src/components/WhatIsUptane/index.jsx
- Putting Uptane: src/components/PuttingUptane/index.jsx
- Join Community: src/components/JoinCommunity/index.jsx
- Adopters: src/components/Adopters/index.jsx

To be honest I'm not very familiar with `.jsx`, but I can try to modify some of them which have the specified content and some of them _seem_ straightforward. However, maybe it might be safer to submit a PR for the .md files mentioned above first, since I'm more familiar with that and then if you want me to try the `.jsx`, I can try to modify some of them in a separate PR? 
Although, I'm not sure if the locations I found above are correct for the `Home Page` , so maybe @hexsecs  can help direct me to where the Home Page is located in the repo? If the Home Page is actually an `.md` file,  I can modify it along with the other .md files specified above. Let me know which of the following is preferred:

a. Create one PR first for the `.md`'s for the About Us, Getting Started, Threat Model, Audio Visual, Contributing, and 
History Pages (and Home Page if it is a .md file).
b. (Assuming Home Page is .jsx) -- Create a separate PR for this and try to modify and/or reassign to someone more familiar with `.jsx`
c. Create one PR for everything (.md and .jsx) for and just modify as much as possible.

**Comment by hexsecs** [comment]
@Mikerniker I assigned to you. For a PR you can add @jhdalek55 @hexsecs and @Abhijay007 as reviewers. BTW, I already fixed the meeting time issue in 7cf1ae5cf77f6dacdf465bf9f86dc05efe8f5d20 as this was a critical issue.

**Comment by hexsecs** [comment]
> I'm not sure if the locations I found above are correct for the `Home Page` , so maybe @hexsecs can help direct me to where the Home Page is located in the repo? If the Home Page is actually an `.md` file, I can modify it along with the other .md files specified above. Let me know which of the following is preferred:
@Abhijay007 may be able to better guide you on how the homepage is created.  


> a. Create one PR first for the `.md`'s for the About Us, Getting Started, Threat Model, Audio Visual, Contributing, and History Pages (and Home Page if it is a .md file). b. (Assuming Home Page is .jsx) -- Create a separate PR for this and try to modify and/or reassign to someone more familiar with `.jsx` c. Create one PR for everything (.md and .jsx) for and just modify as much as possible.
If you want to break it up into PRs for tasks or groups of tasks, that's fine.

**Comment by Mikerniker** [comment]
Ok, I'll start with the .md files first and if @Abhijay007 has recommendations for how to work on the Home Page, will try to send a separate PR for that and will check off the completed tasks.

**Comment by Mikerniker** [comment]
Ok @Abhijay007,  I think I've located the sections to modify in the Home Page and tested the changes locally. Will send a PR for the changes to the Home Page and let me know if there are any issues. Thank you
