### ISSUE TITLE
[Bug Report] - Governance page missing?

### ISSUE THREAD

**Issue by trishankatdatadog** [uptane/uptane.github.io#136]
### Describe the bug.

I'm not sure whether the governance has changed, but certainly the [page](https://uptane.github.io/governance.html) seems to be missing now...

### Describe the steps to reproduce the behavior.

1. Go to https://uptane.github.io/governance.html
2. Text says: "Page is not found"

### Expected behavior.

Page should either be not generated at all with a link to it, or the content needs to be updated.

**Comment by jhdalek55** [comment]
The text of the governance and people pages from the original website was merged into one page, now called "About Us." The relevant text can be found at https://uptane.github.io/docs/learn-more/about.

**Comment by trishankatdatadog** [comment]
Got it, thanks for the quick reply, Lois. There was previously an "advisory group," no? In any case, the link above is somehow still being indexed by Google.

**Comment by jhdalek55** [comment]
Yes. It's good you called this to our attention because that link should no longer be out there. 

As far as the "advisory group goes," when we were revamping the website, we decided to remove that particular listing because technically the only official "board" for Uptane was the three member steering committee mandated by our membership in JDF. No official criteria, at least my knowledge, had ever been set up for who qualifies for this advisory group. Instead, we just updated the company and individual contributors list. Everyone on that advisory group should now be recognized as a contributor.

**Comment by hexsecs** [comment]
We had discussed having a separate list of "voting" versus "email-list" type members. At this point it hasn't been implemented yet. Based on this ticket focusing on the advisory group, can we close the ticket? It was intentionally removed.

**Comment by jhdalek55** [comment]
@hexsecs when we discussed the "active members" list, the consensus was that such a list would be prepared, but it would be maintained offline. So, there is no need to keep an open issue on the website about this,

**Comment by Abhijay007** [comment]
closed as resloved
