### ISSUE TITLE
Improvements to uptane.org domain

### ISSUE THREAD

**Issue by hexsecs** [uptane/uptane.github.io#59]
Currently http://uptane.org (https://uptane.org is broken) redirects to https://uptane.github.io. It is possible for github pages to directly support serving the page at the custom domain address. Should we configure our site to support this? IMO, the page would look considerably more "official" sitting at the uptane.org domain.

Additional info for supporting this:
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by Abhijay007** [comment]
@hexsecs as you have the special org access now, I believe you can set the custom domain for the site, and instead of using: https://uptane.github.io/, we can now use https://uptane.org/ as a custom site domain for the official uptane site, the: https://uptane.github.io/  is still be live but using:  https://uptane.org/  will be more preferable, both the domain will point to the same. 

in order to set the custom domain you can go to the pages under settings and on the scroll you will see a custom domain tab simply just add the custom domain there (which is: https://uptane.org/) and don't forget to enforce HTTPS 

it might require further configurations, not sure about that but the links you mentioned in the issues description will be used for the same.

**Comment by hexsecs** [comment]
@Abhijay007  - I think we need @JustinCappos to adjust the dns entries. Right now it's a redirect I believe.

**Comment by JustinCappos** [comment]
Okay, I've done this.  Right now, I've set it as a temporary redirect (301), but will change that to a permanent redirect (302) once it is confirmed this is working right.  It does look correct to me, but please check.

**Comment by hexsecs** [comment]
@JustinCappos, github can allow actually serving the page from the custom domain. So instead of a redirect, it would actually be served as https://uptane.org/docs/...

The instructions on doing this are here..
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by hexsecs** [comment]
It's fairly straightforward, but it needs the domain owner to add the correct domain records to point to github.

**Comment by hexsecs** [comment]
Working! Thanks @JustinCappos !
